module.exports={   
    API_URL:'http://localhost:8080',
    statuses:['Pending','Paid','NotPaid'],
    //countries:['Eritrea','Ethiopia','Canada','Uganda'],
    countries: ["Afghanistan","Albania","Algeria","Andorra","Angola","Anguilla",
    "Antigua &amp; Barbuda","Argentina","Armenia","Aruba","Australia","Austria","Azerbaijan",
    "Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bermuda",
    "Bhutan","Bolivia","Bosnia &amp; Herzegovina","Botswana","Brazil","British Virgin Islands",
    "Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Cape Verde","Cayman Islands",
    "Chad","Chile","China","Colombia","Congo","Cook Islands","Costa Rica","Cote D Ivoire",
    "Croatia","Cruise Ship","Cuba","Cyprus","Czech Republic","Denmark","Djibouti","Dominica",
    "Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Estonia","Ethiopia","Eritrea",
    "Falkland Islands","Faroe Islands","Fiji","Finland","France","French Polynesia","French West Indies",
    "Gabon","Gambia","Georgia","Germany","Ghana","Gibraltar","Greece","Greenland","Grenada",
    "Guam","Guatemala","Guernsey","Guinea","Guinea Bissau","Guyana","Haiti","Honduras",
    "Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man",
    "Israel","Italy","Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kuwait",
    "Kyrgyz Republic","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein",
    "Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives",
    "Mali","Malta","Mauritania","Mauritius","Mexico","Moldova","Monaco","Mongolia","Montenegro",
    "Montserrat","Morocco","Mozambique","Namibia","Nepal","Netherlands","Netherlands Antilles",
    "New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Norway","Oman","Pakistan",
    "Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal",
    "Puerto Rico","Qatar","Reunion","Romania","Russia","Rwanda","Saint Pierre &amp; Miquelon",
    "Samoa","San Marino","Satellite","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone",
    "Singapore","Slovakia","Slovenia","South Africa","South Korea","Spain","Sri Lanka","St Kitts &amp; Nevis",
    "St Lucia","St Vincent","St. Lucia","Sudan","Suriname","Swaziland","Sweden","Switzerland",
    "Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor L'Este","Togo","Tonga","Trinidad &amp; Tobago",
    "Tunisia","Turkey","Turkmenistan","Turks &amp; Caicos","Uganda","Ukraine","United Arab Emirates",
    "United Kingdom","Uruguay","Uzbekistan","Venezuela","Vietnam","Virgin Islands (US)","Yemen",
    "Zambia","Zimbabwe"],
    
    
    currencies:['Albania Lek','Afghanistan Afghani','Argentina Peso','Aruba Guilder', 'Australia Dollar','Azerbaijan New Manat',
    'Bahamas Dollar', 'Barbados Dollar','Bangladeshi taka','Belarus Ruble', 'Belize Dollar','Bermuda Dollar','Bolivia Boliviano',
    'Botswana Pula', 'Bulgaria Lev', 'Brazil Real','Brunei Darussalam Dollar',
    'Cambodia Riel', 'Canada Dollar','Cayman Islands Dollar','Chile Peso', 'China Yuan Renminbi','Colombia Peso',
    'Costa Rica Colon','Croatia Kuna', 'Cuba Peso', 'Czech Republic Koruna', 'Denmark Krone','Dominican Republic Peso',
    'East Caribbean Dollar', 'Egypt Pound', 'El Salvador Colon', 'Estonia Kroon', 'Eritrea Nalfa','Ethiopia Birr',
    'Euro Member Countries','Falkland Islands (Malvinas) Pound',
     'Fiji Dollar','Ghana Cedis','Gibraltar Pound','Guatemala Quetzal', 'Guernsey Pound','Guyana Dollar',
    'Hong Kong Dollar', 'Hungary Forint', 'Iceland Krona', 'India Rupee','Indonesia Rupiah', 'Iran Rial',
    'Isle of Man Pound','Israel Shekel', 'Jamaica Dollar', 'Japan Yen', 'Jersey Pound', 'Kazakhstan Tenge','Korea (North) Won',
    'Korea (South) Won', 'Kyrgyzstan Som', 'Laos Kip', 'Latvia Lat', 'Lebanon Pound', 'Liberia Dollar', 'Lithuania Litas',
    'Macedonia Denar', 'Malaysia Ringgit','Mauritius Rupee', 'Mexico Peso', 'Mongolia Tughrik', 'Mozambique Metical', 'Namibia Dollar',
    'Netherlands Antilles Guilder', 'New Zealand Dollar', 'Nicaragua Cordoba', 'Nigeria Naira', 'Norway Krone',
    'Oman Rial','Pakistan Rupee', 'Philippines Peso', 'Poland Zloty', 'Qatar Riyal', 'Romania New Leu', 'Russia Ruble',
     'Saint Helena Pound', 'Saudi Arabia Riyal', 'Serbia Dinar', 'Seychelles Rupee', 'Singapore Dollar', 'Somalia Shilling','Sudanese pound','Ugandan shilling',
    'South Africa Rand', 'Sweden Krona', 'Switzerland Franc', 'Syria Pound', 'Taiwan New Dollar', 'Turkey Lira', 'Ukraine Hryvna',
    'United Kingdom Pound','United States Dollar','Zimbabwe Dollar' ],
    host:'localhost',
    user:'root',
    password:'hani1984',
    database:'demodb',
    port:'3306'
   
}